apiVersion: v1
kind: Service
metadata:
    name: playlist
spec:
    selector:
    # This app must match the label of the pods.
        app: g02-playlistserver
    ports:
      - protocol: TCP
        port: 80
        targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: g02-playlistserver
spec:
    selector:
        matchLabels:
            app: g02-playlistserver
    replicas: 1
    template:
        metadata:
            labels:
                app: g02-playlistserver
        spec:
            imagePullSecrets:
                - name: sdugitlab
            containers:
            - name: g02-playlistserver
              image: IMAGE_IS_INSERTED_USING_GITLAB
              imagePullPolicy: Always
              ports:
              - containerPort: 3000
              resources:
                  requests:
                      cpu: "100m"
                      memory: "150Mi"
                  limits:
                      cpu: "200m"
                      memory: "250Mi"
              env:
                  - name: MONGODB_HOST
                    value: "g02-playlistmongodb"
                  - name: MONGODB_PORT
                    value: "27017"
                  - name: MONGODB_DB_NAME
                    value: "g02-playlist"
                
---
apiVersion: v1
kind: Service
metadata:
    name: g02-playlistmongodb
spec:
    selector:
        # This app must match the label of the pods.
        app: g02-playlistmongodb
    ports:
      - protocol: TCP
        name: mongo
        port: 27017
        targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: g02-playlistmongodb
spec:
    selector:
        matchLabels:
            app: g02-playlistmongodb
    replicas: 1
    template:
        metadata:
            labels:
                app: g02-playlistmongodb
        spec:
            containers:
            - name: g02-playlistmongodb
              image: mongo:latest
              ports:
              - containerPort: 27017
              resources:
                  requests:
                      cpu: "100m"
                      memory: "300Mi"
                  limits:
                      cpu: "100m"
                      memory: "400Mi"
              volumeMounts:
              - name: g02-playlistmongodb-init
                mountPath: /etc/mongod.conf
              - name: g02-playlistmongodb-data
                mountPath: /data/db
            volumes:
            - name: g02-playlistmongodb-init
              configMap:
                  name: g02-playlistmongodb-init-config
            - name: g02-playlistmongodb-data
              persistentVolumeClaim:
                  claimName: g02-playlistmongodb-data-claim
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: g02-playlistmongodb-init-config
    labels:
        app: g02-playlistmongodb
data:
    mongodb.conf: |
        net:
            bindIpAll: true
        storage:
            dbPath: /data/db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: g02-playlistmongodb-data-claim
  labels:
      app: g02-playlistmongodb
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
