version: '3.4'

services:
  nodeserver:
    image: playlistserver
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_DB_NAME: playlist
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - 27016:27017
    volumes:
      - data:/data/db

volumes:
  data:
